"""Canonical schemas, column mappings, and controlled vocabularies."""
from __future__ import annotations

from typing import Dict, List

# Deduplication key candidates by feed
DEDUPLICATION_KEYS: Dict[str, List[str]] = {
    "bids": ["bidNtceNo", "bidNtceOrd", "bidClsfcNo", "rbidNo"],
    "awards": ["bidNtceNo", "bidNtceOrd", "bidprcCorpBizrno", "opengRank", "dqlfctnRsn"],
    "contracts": ["untyCntrctNo", "cntrctNo", "cntrctOrd", "cntrctRefNo"],
    "bidder_outcomes": ["bid_notice_no", "bid_notice_round", "bidder_business_registration_no"],
}

# English canonical mappings for standard API feeds
BIDS_API_ALIASES: Dict[str, str] = {
    "bidNtceNo": "bid_notice_no",
    "bidNtceOrd": "bid_notice_round",
    "bidClsfcNo": "bid_classification_no",
    "rbidNo": "rebid_no",
    "bidNtceNm": "bid_title_ko",
    "ntceInsttCd": "notice_agency_code",
    "ntceInsttNm": "notice_agency_name_ko",
    "ntceInsttOfclNm": "notice_agency_official_name",
    "ntceInsttOfclTel": "notice_agency_official_tel",
    "ntceInsttOfclEmailAdrs": "notice_agency_official_email",
    "dmndInsttCd": "demand_agency_code",
    "dmndInsttNm": "demand_agency_name_ko",
    "dmndInsttOfclNm": "demand_agency_official_name",
    "dmndInsttOfclTel": "demand_agency_official_tel",
    "dmndInsttOfclEmailAdrs": "demand_agency_official_email",
    "dminsttCd": "demand_agency_code",
    "dminsttNm": "demand_agency_name_ko",
    "bidNtceDt": "bid_notice_date",
    "bidNtceDate": "bid_notice_date",
    "bidNtceBgn": "bid_notice_time",
    "bidNtceBgnDt": "bid_notice_begin_datetime",
    "bidNtceEndDt": "bid_notice_end_datetime",
    "bidBeginDate": "bid_begin_date",
    "bidBeginTm": "bid_begin_time",
    "bidClseDate": "bid_close_date",
    "bidClseTm": "bid_close_time",
    "opengDt": "opening_datetime",
    "opengDate": "opening_date",
    "opengTm": "opening_time",
    "opengPlce": "opening_place_ko",
    "asignBdgtAmt": "assigned_budget_krw",
    "presmPtce": "estimated_price_krw",
    "presmptPrce": "estimated_price_krw",
    "bsisAmt": "base_amount_krw",
    "bsnsDivCd": "business_div_code",
    "bsnsDivNm": "business_div_name_ko",
    "cntrctCnclsMthdNm": "contract_method_ko",
    "cntrctCnclsSttusNm": "contract_status_ko",
    "bidwinrDcsnMthdNm": "award_method_ko",
    "sucsfbidMthdNm": "award_method_ko",
    "sucsfbidLwltRate": "award_lower_limit_rate",
    "refNtceNo": "ref_notice_no",
    "refNtceOrd": "ref_notice_round",
    "bidNtceUrl": "bid_notice_url",
    "dataBssDate": "data_base_date",
    "cmmnCntrctYn": "is_joint_contract",
    "elctrnBidYn": "is_electronic_bid",
    "intrntnlBidYn": "is_international_bid",
    "ppsNtceYn": "is_pps_notice",
    "rgnLmtYn": "is_region_limited",
    "indstrytyLmtYn": "is_industry_limited",
}

AWARDS_API_ALIASES: Dict[str, str] = {
    "bidNtceNo": "bid_notice_no",
    "bidNtceOrd": "bid_notice_round",
    "bidClsfcNo": "bid_classification_no",
    "rbidNo": "rebid_no",
    "bidNtceNm": "bid_title_ko",
    "bsnsDivCd": "business_div_code",
    "bsnsDivNm": "business_div_name_ko",
    "cntrctCnclsSttusNm": "contract_status_ko",
    "cntrctCnclsMthdNm": "contract_method_ko",
    "bidwinrDcsnMthdNm": "award_method_ko",
    "ntceInsttCd": "notice_agency_code",
    "ntceInsttNm": "notice_agency_name_ko",
    "dmndInsttCd": "demand_agency_code",
    "dmndInsttNm": "demand_agency_name_ko",
    "dminsttNm": "demand_agency_name_ko",
    "sucsfLwstlmtRt": "award_lower_limit_rate",
    "sucsfbidLwltRate": "award_lower_limit_rate",
    "presmPtce": "estimated_price_krw",
    "presmptPrce": "estimated_price_krw",
    "rsrvtnPrce": "scheduled_price_krw",
    "plndPrice": "scheduled_price_krw",
    "bssAmt": "base_amount_krw",
    "bsisAmt": "base_amount_krw",
    "opengDt": "opening_datetime",
    "opengDate": "opening_date",
    "opengTm": "opening_time",
    "opengRsltDivNm": "opening_result_status_ko",
    "opengRank": "opening_rank",
    "bidprcCorpBizrno": "bidder_business_registration_no",
    "bidprcCorpNm": "bidder_name_ko",
    "bidprcCorpCeoNm": "bidder_ceo_name",
    "bidprcAmt": "bid_amount_krw",
    "bidprcRt": "bid_rate",
    "bidprcDate": "bid_submission_date",
    "bidprcTm": "bid_submission_time",
    "sucsfYn": "is_selected_winner",
    "dqlfctnRsn": "disqualification_reason_ko",
    "fnlSucsfAmt": "award_amount_krw",
    "sucsfbidAmt": "award_amount_krw",
    "fnlSucsfRt": "award_rate",
    "sucsfbidRate": "award_rate",
    "fnlSucsfDate": "award_date",
    "fnlSucsfCorpNm": "winner_name_ko",
    "corpNm": "winner_name_ko",
    "fnlSucsfCorpBizrno": "winner_business_registration_no",
    "bizno": "winner_business_registration_no",
    "fnlSucsfCorpCeoNm": "winner_ceo_name",
    "fnlSucsfCorpAdrs": "winner_address",
    "fnlSucsfCorpContactTel": "winner_contact_tel",
    "dataBssDate": "data_base_date",
}

CONTRACTS_API_ALIASES: Dict[str, str] = {
    "untyCntrctNo": "unified_contract_no",
    "cntrctNo": "contract_no",
    "cntrctOrd": "contract_round",
    "cntrctRefNo": "contract_ref_no",
    "cntrctNm": "contract_title_ko",
    "cntrctCnclsDate": "contract_date",
    "cntrctCnclsMthdNm": "contract_method_ko",
    "cntrctCnclsSttusNm": "contract_status_ko",
    "cntrctAmt": "contract_amount_krw",
    "ttalCntrctAmt": "total_contract_amount_krw",
    "totCntrctAmt": "total_contract_amount_krw",
    "cntrctInsttCd": "contract_agency_code",
    "cntrctInsttNm": "contract_agency_name_ko",
    "cntrctInsttChrgDeptNm": "contract_agency_dept_name",
    "cntrctInsttOfclNm": "contract_agency_official_name",
    "cntrctInsttOfclTel": "contract_agency_official_tel",
    "dmndInsttCd": "demand_agency_code",
    "dmndInsttNm": "demand_agency_name_ko",
    "dminsttCd": "demand_agency_code",
    "dminsttNm": "demand_agency_name_ko",
    "dmndInsttOfclNm": "demand_agency_official_name",
    "dmndInsttOfclTel": "demand_agency_official_tel",
    "rprsntCorpBizrno": "contractor_business_registration_no",
    "bizno": "contractor_business_registration_no",
    "rprsntCorpNm": "contractor_name_ko",
    "corpNm": "contractor_name_ko",
    "rprsntCorpCeoNm": "contractor_ceo_name",
    "rprsntCorpAdrs": "contractor_address",
    "rprsntCorpContactTel": "contractor_contact_tel",
    "bidNtceNo": "bid_notice_no",
    "bidNtceOrd": "bid_notice_round",
    "bidNtceNm": "bid_title_ko",
    "bidNtceUrl": "bid_notice_url",
    "cntrctInfoUrl": "contract_info_url",
    "cntrctPrd": "contract_period",
    "lngtrmCtnuDivNm": "long_term_contract_div_ko",
    "prvtcntrctRsn": "private_contract_reason_ko",
    "cntrctMthdNm": "contract_method_ko",
    "dataBssDate": "data_base_date",
    "cmmnCntrctYn": "is_joint_contract",
    "dmstcCorpYn": "is_domestic_corp",
}

# Bidder Report Export Aliases
BIDDER_REPORT_ALIASES: Dict[str, str] = {
    "조달방식": "procurement_channel",
    "업무구분": "business_type",
    "입찰방법": "bidding_method",
    "계약구분": "contract_type",
    "입찰공고번호": "bid_notice_no",
    "입찰공고차수": "bid_notice_round",
    "입찰분류번호": "bid_classification_no",
    "공고명": "bid_title_ko",
    "공고일자": "bid_notice_date",
    "공고기관코드": "notice_agency_code",
    "공고기관": "notice_agency_name_ko",
    "수요기관코드": "demand_agency_code",
    "수요기관": "demand_agency_name_ko",
    "계약방법": "contract_method",
    "낙찰방법": "award_method",
    "적용계약법": "applicable_contract_law",
    "조항호내용": "legal_clause_text_ko",
    "개찰일자": "opening_date",
    "공공조달분류": "public_procurement_classification",
    "공동도급구성방식": "joint_contract_structure",
    "면허업종제한목록": "license_restrictions_ko",
    "세부품명번호목록": "item_detail_codes",
    "제한지역목록": "region_restrictions_ko",
    "공동도급지역목록": "joint_contract_regions_ko",
    "공사현장": "construction_site_ko",
    "정보화사업여부": "is_it_project",
    "긴급공고여부": "is_urgent_notice",
    "지역의무공동도급여부": "is_mandatory_regional_joint_contract",
    "소관구분": "jurisdiction_type",
    "수요기관소재시군구": "demand_agency_sigungu_ko",
    "배정예산": "allocated_budget_krw",
    "추정가격": "estimated_price_krw",
    "유찰여부": "is_failed_bid",
    "기초금액": "base_amount_krw",
    "예정가격": "scheduled_price_krw",
    "개찰순위": "opening_rank",
    "낙찰자선정여부": "is_selected_winner",
    "업체명": "bidder_name_ko",
    "업체사업자등록번호": "bidder_business_registration_no",
    "투찰일자": "bid_submission_date",
    "투찰금액": "bid_amount_krw",
    "투찰율": "bid_rate",
    "부적격여부": "is_disqualified",
    "입찰부적격사유": "disqualification_reason_ko",
    "업체소재시군구": "bidder_sigungu_ko",
    "계약번호": "contract_no",
    "계약일자": "contract_date",
    "계약시점기업구분": "company_class_at_contract",
    "신규장기구분": "new_or_long_term_contract",
    "금차계약금액": "current_contract_amount_krw",
    "총계약금액": "total_contract_amount_krw",
}

# Controlled categorical value mappings
CONTROLLED_CATEGORIES: Dict[str, Dict[str, str]] = {
    "business_div": {
        "1": "goods",
        "2": "foreign",
        "3": "construction",
        "5": "service",
        "물품": "goods",
        "외자": "foreign",
        "공사": "construction",
        "용역": "service",
    },
    "boolean_yn": {
        "Y": "true",
        "N": "false",
        "y": "true",
        "n": "false",
        "여": "true",
        "부": "false",
        "1": "true",
        "0": "false",
    }
}
